version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install lxml
          command: pip install lxml
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Build python package
          command: |
            python -m pip install --upgrade setuptools
            python -m pip install --upgrade pip
            python -m pip install --upgrade build
            python -m pip install --upgrade wheel
            pip install -r requirements.txt
            python -m build -s --no-isolation --wheel
      - run:
          name: Run tests
          command: python -m pytest
workflows:
  ats_utilities:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: master

