name: ats_utilities_python_checker

on:
  push:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'setup.py'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check module length and line limits
        run: |
          python3 gates/gates/limits_checker.py ats_utilities
