name: ats_utilities_srp_checker

on:
  push:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'

permissions:
  contents: read

jobs:
  srp_gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check Single Responsibility Principle violations
        run: |
          python3 gates/gates/srp_checker.py ats_utilities
