name: ats_utilities build python2 package
on:
  push:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - name: install dependencies
      run: |
        python2 -m pip install --upgrade setuptools
        python2 -m pip install --upgrade pip
        python2 -m pip install --upgrade build
        python2 -m pip install --upgrade wheel
        pip2 install -r requirements.txt
    - name: build by python build
      run: |
        python2 -m build -s --no-isolation --wheel
    - name: build by python setup
      run: |
        python2 setup.py sdist bdist_wheel
