name: ats_utilities_coverage
on:
  push:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'tests/**'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'tests/**'
      - 'setup.py'
jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v4
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install coverage
    - name: Run tests with coverage
      run: |
        cd tests
        python3 -m coverage run -m --source=../ats_utilities unittest discover -s ./ -p '*_test.py' -vvv
        python3 -m coverage html -d htmcov
        python3 -m coverage xml - o ats_utilities_coverage.xml
        python3 -m coverage json -o ats_utilities_coverage.json
        python3 -m coverage report --format=markdown -m
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          tests/htmlcov
          tests/ats_utilities_coverage.xml
          tests/ats_utilities_coverage.json
    - name: Parse coverage and update README
      run: |
          cd tests
          python3 ats_coverage.py -n ats_utilities
