name: ats_utilities_docker_checker
on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ats_utilities_docker_checker
      id: docker_checker
      run: |
        echo Building Docker image
        build_transcript=$(docker build . --file Dockerfile --tag ats_utilities:latest)
        [[ "$build_transcript" == *"Successfully"* ]] && echo "All looks good" || exit 1
