name: Install Python3 Package ats_utilities
on:
  push:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade setuptools
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade build
        python3 -m pip install --upgrade wheel
        pip3 install -r requirements.txt
    - name: Build by python build
      run: |
        python3 -m build -s --no-isolation --wheel
    - name: Build and publish
      run: |
        python3 setup.py --github sdist bdist_wheel
