on: [push]
jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: Delete workflow runs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete workflow runs
        uses: MajorScruffy/delete-workflow-runs
        id: delete-workflow-runs
        with:
          repository: vroncevic/ats_utilities
          older-than-seconds: 86400
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
