name: ats_utilities_python3_build

on:
  push:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'ats_utilities/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v4

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools build wheel
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: Build python3 package
      run: |
        python3 -m build -s --no-isolation --wheel

    - name: Build python3 package setup
      run: |
        python3 setup.py sdist bdist_wheel